version: '3'

services:
  api:
    env_file: .env
    container_name: "coding-blocks-website"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        PORT: ${PORT}
    environment:
      - 'PORT=${PORT}'
    ports:
      - "${PORT}:${PORT}"

    networks:
      - codingblocks
    restart: 'always'
    command: pm2-docker start /home/node/app/pm2.json --web 4545
networks:
  codingblocks:
    external: true
